### ISSUE TITLE
折线图和条形图都无法显示

### ISSUE THREAD

**Issue by NightFog007** [hypersport/sysinfo#1]
大神,请问文字可以正常显示,但是折线图和条形图都无法显示是什么原因啊? 

![2](https://user-images.githubusercontent.com/59461157/82106299-9ae47f80-9752-11ea-9685-d276041c89e2.png)
![1](https://user-images.githubusercontent.com/59461157/82106306-9fa93380-9752-11ea-92a7-4157ae10342f.png)

**Comment by zbaolong** [comment]
作者在改吧

**Comment by hypersport** [comment]
感谢，问题已解决。
